### ISSUE TITLE
does optimization happen on GPU?

### ISSUE THREAD

**Issue by Sandy4321** [dstein64/PyFactorizationMachines#1]
may you clarify if your code uses GPU?
since it is very slow 
how long example file calculation lasts?

**Comment by dstein64** [comment]
Hi @Sandy4321,

Training will use the GPU if Theano is configured to use the GPU.

Theano can be configured with a `.theanorc` file or using the `THEANO_FLAGS` environment variable. This page has instructions for configuring Theano to use the GPU.
http://deeplearning.net/software/theano/tutorial/using_gpu.html

For example, running your program like this should use the GPU.
`THEANO_FLAGS=device=gpu python program.py`

`device=gpu` may have to be changed depending on your version of Theano. It may have to be changed to `device=cuda` or some alternative.

**Comment by Sandy4321** [comment]
I see, 
thanks for soon answer,
may you clarify what time it takes to calculate example file with GPU (what GPU you use?) and without GPU

By the way , if Adam optimization happen on GPU?
and what part of calculation happen on GPU and what not?

**Comment by dstein64** [comment]
> "may you clarify what time it takes to calculate example file with GPU (what GPU you use?) and without GPU"

I timed the first call to `fit` in example.py ([line 33](https://github.com/dstein64/PyFactorizationMachines/blob/master/example.py#L33)).

For the GPU, I ran the code an initial time, and then timed the code when running a second time. I did this because for the first call, CUDA code has to be compiled, which is slow.

With CPU (no GPU), the code takes 50 seconds.
With GPU, the code takes 773 seconds.

My CPU is a Core i7 2.8GHz and my GPU is a GeForce GT 730M.

This is consistent with experiments I've ran in the past using neural networks, where I found that small problems are slower on a GPU (due to the increased latency). However, I've found larger problems (larger networks, larger number of input features) are faster on the GPU (due to increased throughput).

**Comment by dstein64** [comment]
> "By the way , if Adam optimization happen on GPU? and what part of calculation happen on GPU and what not?"

When using GPU, the Theano functions ([line 142](https://github.com/dstein64/PyFactorizationMachines/blob/master/pyfms/core.py#L142)) are executed on the GPU. This includes the Adam optimization. All other functionality (e.g., printing to the screen, looping over data, etc.) is executed on the CPU.

**Comment by Sandy4321** [comment]
Dear Daniel, 
Thank you very much ,
Only one more , may you add test for sparsity  to Binary Classification Example
print('*******************************************')
print('* Binary Classification Example')
print('* (with verbose output)')
print('*******************************************')
 
since , it is the most popular case to  use FM for spars binary classification.
Thank you very much in advance
Sandy

**Comment by dstein64** [comment]
@Sandy4321, the example usage of sparse data was moved from the regression example to the classification example. Please note that the sparsity options work the same for regression and classification, as it's a function of the features, not the target.

**Comment by Sandy4321** [comment]
Great thanks for soon answer
Please review calculation result if it is correct
on my i7 1 year old laptop it took ~40 minutes,only for classification
Microsoft Windows [Version 10.0.16299.371]
(c) 2017 Microsoft Corporation. All rights reserved.

E:\PyFactorizationMachines_May2\PyFactorizationMachines>python example.py
WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
C:\Users\sndr\Anaconda3\lib\site-packages\theano\configdefaults.py:560: UserWarning: DeprecationWarning: there is no c++ compiler.This is deprecated and with Theano 0.11 a c++ compiler will be mandatory
  warnings.warn("DeprecationWarning: there is no c++ compiler."
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
pyfms 0.2.6

*******************************************
* Binary Classification Example
* (with sparse data and verbose output)
*******************************************

Epoch 5000/20000
 loss: 0.30130738257526263, min_loss: 0.300115335584102
Epoch 10000/20000
 loss: 0.29844043498474954, min_loss: 0.2980589561544978
Epoch 15000/20000
 loss: 0.2974378413176969, min_loss: 0.2969931393729082
Epoch 20000/20000
 loss: 0.29708510541644345, min_loss: 0.29620692691564143

Factorization Machine Error: 0.12745098039215685
Logistic Regression Error: 0.1470588235294118

**Comment by dstein64** [comment]
On my 3 year old i7 laptop, the example.py script takes 2 minutes and 20 seconds.

Based on the warnings you pasted, g++ is not available, and "Performance will be severely degraded". The warnings suggest installing `m2w64-toolchain`.
```conda install m2w64-toolchain```
