### ISSUE TITLE
do you have special code for sparse data?

### ISSUE THREAD

**Issue by Sandy4321** [dstein64/PyFactorizationMachines#2]
is your code running faster of sparse data?

**Comment by dstein64** [comment]
Hi @Sandy4321, my code has not been optimized to run on sparse data, although sparse data is supported as long as it's represented by a dense numpy matrix with 0s.

There is a [fork](https://github.com/srome/PyFactorizationMachines) of the project that adds support for sparse matrices. However, that is currently 41 commits behind this project.

**Comment by Sandy4321** [comment]
Hello 

It is exactly how I found your code by using this link
https://github.com/srome/PyFactorizationMachines
The problem with link is that there is no advanced optimization like Adam and GPU use
But problem with your code is, that sparse data representation is not used, so big matrices can not be used.
For example data from this link 
https://github.com/srome/PyFactorizationMachines
can not be represented in dense matrix , since it uses huge matrix , that can not be placed in RAM
Can you try to use sparse matrix ?

**Comment by dstein64** [comment]
@Sandy4321, pyfms version 0.2.6 now has support for sparse data. Please see the documentation and example for usage details.
