### ISSUE TITLE
can be regularities used for classifier?

### ISSUE THREAD

**Issue by Sandy4321** [dstein64/PyFactorizationMachines#5]
this code
    reg = regularizers.L2(0, 0, .01)
    fm_classifier = Classifier(X_t.shape[1] , k=2, X_format="csr",regularizer=reg)
gives error:
File "E:\Recommender_systems\code\PyFactorizationMachines_May2\PyFactorizationMachines\S_May3_changed_hashing_size_Theano_FM_sparse.py", line 74, in <module>
  fm_classifier = Classifier(X_t.shape[1] , k=2, X_format="csr",regularizer=reg)
File "E:\Recommender_systems\code\PyFactorizationMachines_May2\PyFactorizationMachines\pyfms\models.py", line 10, in __init__
  feature_count, transformer, **kwargs)

builtins.TypeError: __init__() got an unexpected keyword argument 'regularizer'

**Comment by dstein64** [comment]
Hi @Sandy4321, the regularizer should be passed to the fit method, not the Classifier constructur.

Something like:
```
reg = regularizers.L2(0, 0, .01)
fm_classifier = Classifier(X_t.shape[1] , k=2, X_format="csr")
fm_classifier .fit(X_t, y_t, regularizer=reg)
```

**Comment by Sandy4321** [comment]
great thanks
by the way 
it would be very kind of you to add L1 regularization as well
the difference in code is not big
http://www.chioka.in/differences-between-l1-and-l2-as-loss-function-and-regularization/

    penalty = (self.beta_w0 * (w0 ** 2)) \
                  + (self.beta_w1 * T.mean(w1 ** 2)) \
                  + (self.beta_v * T.mean(v ** 2))
will have change ** by abs??

**Comment by dstein64** [comment]
> it would be very kind of you to add L1 regularization as well

Done (1ee9dad19fb477ceada8a7f256bc177526762281).

Please note that the code is extensible. That is, if there is a type of regularization that you would like to use, which is not already included, you can define a regularization class in your code, and use it as the regularizer.

**Comment by Sandy4321** [comment]
great thanks
interesting that with L1 starts with 2 times less loss than L2
regularizer is  L1
Epoch 5/50
 loss: 0.06345012873425997, min_loss: 0.06345012873425997
regularizer is  L2
Epoch 5/50
 loss: 0.1324381194926894, min_loss: 0.11444410052788664

but at the end both gives the same performance,
though without proper treating unbalanced data both are not valid at all

**Comment by Sandy4321** [comment]
used code is 
#S_May6_NLP_data_Theano_FM_sparse.py
#https://github.com/dstein64/PyFactorizationMachines/issues/5
#reg = regularizers.L2(0, 0, .01)
#fm_classifier = Classifier(X_t.shape[1] , k=2, X_format="csr")
#fm_classifier .fit(X_t, y_t, regularizer=reg)


#https://github.com/dstein64/PyFactorizationMachines/issues/6
#v has the parameters for the interaction terms, w0 has the bias term paramater, and w1 has the first-order term parameters.

#These can be accessed with the get_weights method. The example below shows how to access the v parameters, 
#and also see how many there are, which is a function of 1) the number of dimensions in your dataset and 2) the value of k.

#w0, w1, v = fm_classifier.get_weights()
#print("v:")
#print(v)
#print("shape(v)")
#print(v.shape)
#print("size(v)")
#print(v.size)

#S_May3_changed_hashing_size_Theano_FM_sparse.py
#C:\Windows\system32>conda install theano    <- good
#conda install m2w64-toolchain <-destroys theano
#S_May2_changed_hashing_size_Theano_FM_sparse.py
#S_May2_hashing_FM_sparse.py
#S_apr25_FM_sparse
#code from
#https://github.com/dstein64/PyFactorizationMachines
#data example from 
#http://srome.github.io/Leveraging-Factorization-Machines-for-Sparse-Data-and-Supervised-Visualization/

if 0:
    import os
    #os.environ["THEANO_FLAGS"] = "mode=FAST_RUN,device=gpu,floatX=float32"
    os.environ["THEANO_FLAGS"] = "mode=FAST_RUN,device=cuda,floatX=float32"


import pickle
import pandas as pd
from sklearn.feature_extraction import FeatureHasher
#original from PyFactorizationMachines.src.pyfm import FactorizationMachineClassifier
from pyfms import Classifier
from pyfms import regularizers
from sklearn.model_selection import train_test_split
from pandas_ml import ConfusionMatrix
import pandas as pd
#parameters
flag_regulariser= 'L2' #'L1' # L2
n_V_dimensions = 6
flag_0_use_all_hash_features_or_1_set_number_of_features =  0
number_of_features_for_Hasher = 12345 #1234 # 123#12345

if 1:
    from sklearn.datasets import fetch_20newsgroups
    twenty_train = fetch_20newsgroups(subset='train', 
                                      shuffle=True, 
                                      random_state=42)
    
    
    
    filehandler = open(b"twenty_data.pkl","wb")
    pickle.dump(twenty_train,filehandler)
else:

    file_name = open("twenty_data.pkl",'rb')
    twenty_train= pickle.load(file_name)
twenty_train.target_names


def define_label(x, target_names):
    name = target_names[x]
    return 1 if 'comp' in name else 0
    
target = pd.Series(twenty_train.target).apply(lambda x : define_label(x,twenty_train.target_names))
target.mean() # Prevalence of the label

q=3
def clean_text(text):
    # Basic cleaning
    text=text.replace('\n','').replace('\t','').replace('<','').replace('>','').replace('|','')
    return [x for x in text.split(' ') if len(x) > 3]

X = [clean_text(x) for x in twenty_train.data]


q=1
# Hash away!
if flag_0_use_all_hash_features_or_1_set_number_of_features:
    fh = FeatureHasher(input_type='string',n_features= number_of_features_for_Hasher, non_negative=True)
else:
    fh = FeatureHasher(input_type='string', non_negative=True) # full number of features
X_t = fh.transform(X)

# Bin the inputs so that the "interaction" terms are more interpretable
X_bin = X_t.copy()
X_bin[X_bin >= 1] = 1
X_train, X_test, y_train, y_test = train_test_split(X_bin, target, test_size=0.33, random_state=42)

if flag_regulariser == 'L2':
    reg = regularizers.L2(0, 0, .01)
if flag_regulariser == 'L1':
    reg = regularizers.L1(0, 0, .01)
    
print('regularizer is ', flag_regulariser)
fm_classifier = Classifier(X_t.shape[1] , k = n_V_dimensions, X_format="csr")
if 0:
    fm_classifier.fit(X_train, y_train.values,  verbosity=5, nb_epoch= 50)# original 
else:
    fm_classifier.fit(X_train, y_train.values,  verbosity=5, nb_epoch= 50, regularizer = reg)


# original as in example.py
#type(y_train)
#<class 'numpy.ndarray'>

#original f.fit(X_train, y_train,  verbosity=50, nb_epoch=200)
# original f.fit(X_train, y_train,  verbosity=5, nb_epoch=20)



q=4
from sklearn.metrics import accuracy_score
def error_score(y_true, y_pred):
    return 1.0 - accuracy_score(y_true, y_pred)
print()
print('Factorization Machine Error: {}'.format(
    error_score(y_test, fm_classifier.predict(X_test))))
q=6

from sklearn.metrics import classification_report
print(          classification_report(  y_test,   fm_classifier.predict(X_test)       ) )

q=6

cm = ConfusionMatrix(y_test.values,   fm_classifier.predict(X_test) )
print('Confusion Matrix')
print(cm)

y_actu = pd.Series(y_test.values, name='Actual')
y_pred = pd.Series(fm_classifier.predict(X_test), name='Predicted')
df_confusion = pd.crosstab(y_actu, y_pred)
print(' \n \n simple confusion matrix')
print(df_confusion)
#cm.print_stats()
q=8
v = fm_classifier.v.eval()
print('len v =', len(v))
print('len v[0] =', len(v[0]))
w1 = fm_classifier.w1.eval()
print('len w1 = ', len(w1) )
w0 = fm_classifier.w0.eval()
print('len w0 = ', len(w0) )
q=7
'''
y_actu = [2, 0, 2, 2, 0, 1, 1, 2, 2, 0, 1, 2]
y_pred = [0, 0, 2, 1, 0, 2, 1, 0, 2, 0, 2, 2]
cm = ConfusionMatrix(y_actu, y_pred)
cm.print_stats()


q=8

import pandas as pd
y_actu = pd.Series([2, 0, 2, 2, 0, 1, 1, 2, 2, 0, 1, 2], name='Actual')
y_pred = pd.Series([0, 0, 2, 1, 0, 2, 1, 0, 2, 0, 2, 2], name='Predicted')
df_confusion = pd.crosstab(y_actu, y_pred)

q=7

'''
