### ISSUE TITLE
can be length of latent vector V changed

### ISSUE THREAD

**Issue by Sandy4321** [dstein64/PyFactorizationMachines#6]
v = fm_classifier.v.eval()
print('len v =', len(v))
print('len v[0] =', len(v[0]))
gives
len v = 2
len v[0] = 12345
when 12345 is number of features

may you share how to preset length of v ?
iris important parameter for optimization
thanks

**Comment by dstein64** [comment]
`v` has the parameters for the interaction terms, `w0` has the bias term paramater, and `w1` has the first-order term parameters.

These can be accessed with the `get_weights` method. The example below shows how to access the `v` parameters, and also see how many there are, which is a function of 1) the number of dimensions in your dataset and 2) the value of k.

```
w0, w1, v = fm_classifier.get_weights()
print("v:")
print(v)
print("shape(v)")
print(v.shape)
print("size(v)")
print(v.size)
```

**Comment by Sandy4321** [comment]
I see, great so parameter K sets dimension for vector V?

**Comment by dstein64** [comment]
> I see, great so parameter K sets dimension for vector V?

`v` is a matrix, not a vector. `k` configures how many rows are in that matrix, and `d` (the number of features) determines how many columns.

`k` is the same parameter defined in the paper on Factorization Machines.
http://www.algo.uni-konstanz.de/members/rendle/pdf/Rendle2010FM.pdf
